sonar.projectKey=sonar-node-app
sonar.projectName=Sonar Node App
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=squ_bfe46ae7e1a1377ec37bd2d93be54bceeb8e5350
